from .contact import Contact
from .external_documentation import ExternalDocumentation
from .info import Info
from .license import License
from .operation import Operation
from .parameter import Parameter
from .parameters import Parameters
from .paths import Paths
from .path import Path
from .response import Response
from .responses import Responses
from .schema import JsonSchemaObject
from .security_requirement import SecurityRequirement
from .swagger import Swagger
from .tag import Tag
